// SEED CONSTANTS

export const CREATED_AT_STRING = '2024-01-01T00:00:00.000Z'
export const CARGO_TYPE_FOOTPRINT_SIZE_BICYCLE = 1
export const CARGO_TYPE_FOOTPRINT_SIZE_MOTORCYCLE = 2
export const CARGO_TYPE_FOOTPRINT_SIZE_ATV = 3
export const CARGO_TYPE_FOOTPRINT_SIZE_CARRIER = 4
export const CARGO_TYPE_FOOTPRINT_SIZE_CAR_SMALL = 5
export const CARGO_TYPE_FOOTPRINT_SIZE_CAR_MEDIUM = 6
export const CARGO_TYPE_FOOTPRINT_SIZE_CAR_LARGE = 7
export const CARGO_TYPE_FOOTPRINT_SIZE_TRUCK = 8
// export const CARGO_TYPE_FOOTPRINT_SIZE_CAR_XL = 8

export const CARGO_TYPE_FOOTPRINT_SIZES = [
  CARGO_TYPE_FOOTPRINT_SIZE_BICYCLE,
  CARGO_TYPE_FOOTPRINT_SIZE_MOTORCYCLE,
  CARGO_TYPE_FOOTPRINT_SIZE_ATV,
  CARGO_TYPE_FOOTPRINT_SIZE_CARRIER,
  CARGO_TYPE_FOOTPRINT_SIZE_CAR_SMALL,
  CARGO_TYPE_FOOTPRINT_SIZE_CAR_MEDIUM,
  CARGO_TYPE_FOOTPRINT_SIZE_CAR_LARGE,
  // CARGO_TYPE_FOOTPRINT_SIZE_CAR_XL,
  CARGO_TYPE_FOOTPRINT_SIZE_TRUCK
]

export const CARGO_TYPE_FOOTPRINT_SIZES_LABELS = [
  'Bicycle',
  'Motorcycle',
  'ATV',
  'Carrier',
  'Car Small',
  'Car Medium',
  'Car Large',
  // 'Car XL',
  'Truck'
]
